### ISSUE TITLE
[ENH] - HCP Pipelines module

### ISSUE THREAD

**Issue by jerdra** [jerdra/BOONStim#15]
The standard pipeline at the moment is the ciftify/fmriprep route, however some acquisitions are better processed using HCP-Pipelines (HCP and potentially ABCD sequences). 

The rest of the pipeline is agnostic to T1 processing and surface generation (as long as they're freesurfer compatible). 

### TO-DO:

- [ ] Build an HCP pipelines module that outputs the required cifti surfaces
- [ ] Wrap the fs2gifti and cifti_mesh workflows into a single workflow, HCP pipeliens doesn't need f2gifti
- [ ] Run HCP sequence data through the pipeline
